// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package deal

import (
	_ "cosmossdk.io/api/amino"
	_ "cosmossdk.io/api/cosmos/base/query/v1beta1"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_NewContract               protoreflect.MessageDescriptor
	fd_NewContract_dealId        protoreflect.FieldDescriptor
	fd_NewContract_contractId    protoreflect.FieldDescriptor
	fd_NewContract_consumer      protoreflect.FieldDescriptor
	fd_NewContract_desc          protoreflect.FieldDescriptor
	fd_NewContract_ownerETA      protoreflect.FieldDescriptor
	fd_NewContract_vendorETA     protoreflect.FieldDescriptor
	fd_NewContract_status        protoreflect.FieldDescriptor
	fd_NewContract_fees          protoreflect.FieldDescriptor
	fd_NewContract_expiry        protoreflect.FieldDescriptor
	fd_NewContract_shippingDelay protoreflect.FieldDescriptor
	fd_NewContract_startTime     protoreflect.FieldDescriptor
	fd_NewContract_deliveryDelay protoreflect.FieldDescriptor
)

func init() {
	file_example_deal_new_contract_proto_init()
	md_NewContract = File_example_deal_new_contract_proto.Messages().ByName("NewContract")
	fd_NewContract_dealId = md_NewContract.Fields().ByName("dealId")
	fd_NewContract_contractId = md_NewContract.Fields().ByName("contractId")
	fd_NewContract_consumer = md_NewContract.Fields().ByName("consumer")
	fd_NewContract_desc = md_NewContract.Fields().ByName("desc")
	fd_NewContract_ownerETA = md_NewContract.Fields().ByName("ownerETA")
	fd_NewContract_vendorETA = md_NewContract.Fields().ByName("vendorETA")
	fd_NewContract_status = md_NewContract.Fields().ByName("status")
	fd_NewContract_fees = md_NewContract.Fields().ByName("fees")
	fd_NewContract_expiry = md_NewContract.Fields().ByName("expiry")
	fd_NewContract_shippingDelay = md_NewContract.Fields().ByName("shippingDelay")
	fd_NewContract_startTime = md_NewContract.Fields().ByName("startTime")
	fd_NewContract_deliveryDelay = md_NewContract.Fields().ByName("deliveryDelay")
}

var _ protoreflect.Message = (*fastReflection_NewContract)(nil)

type fastReflection_NewContract NewContract

func (x *NewContract) ProtoReflect() protoreflect.Message {
	return (*fastReflection_NewContract)(x)
}

func (x *NewContract) slowProtoReflect() protoreflect.Message {
	mi := &file_example_deal_new_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_NewContract_messageType fastReflection_NewContract_messageType
var _ protoreflect.MessageType = fastReflection_NewContract_messageType{}

type fastReflection_NewContract_messageType struct{}

func (x fastReflection_NewContract_messageType) Zero() protoreflect.Message {
	return (*fastReflection_NewContract)(nil)
}
func (x fastReflection_NewContract_messageType) New() protoreflect.Message {
	return new(fastReflection_NewContract)
}
func (x fastReflection_NewContract_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_NewContract
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_NewContract) Descriptor() protoreflect.MessageDescriptor {
	return md_NewContract
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_NewContract) Type() protoreflect.MessageType {
	return _fastReflection_NewContract_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_NewContract) New() protoreflect.Message {
	return new(fastReflection_NewContract)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_NewContract) Interface() protoreflect.ProtoMessage {
	return (*NewContract)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_NewContract) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.DealId != "" {
		value := protoreflect.ValueOfString(x.DealId)
		if !f(fd_NewContract_dealId, value) {
			return
		}
	}
	if x.ContractId != "" {
		value := protoreflect.ValueOfString(x.ContractId)
		if !f(fd_NewContract_contractId, value) {
			return
		}
	}
	if x.Consumer != "" {
		value := protoreflect.ValueOfString(x.Consumer)
		if !f(fd_NewContract_consumer, value) {
			return
		}
	}
	if x.Desc != "" {
		value := protoreflect.ValueOfString(x.Desc)
		if !f(fd_NewContract_desc, value) {
			return
		}
	}
	if x.OwnerETA != uint32(0) {
		value := protoreflect.ValueOfUint32(x.OwnerETA)
		if !f(fd_NewContract_ownerETA, value) {
			return
		}
	}
	if x.VendorETA != uint32(0) {
		value := protoreflect.ValueOfUint32(x.VendorETA)
		if !f(fd_NewContract_vendorETA, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_NewContract_status, value) {
			return
		}
	}
	if x.Fees != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Fees)
		if !f(fd_NewContract_fees, value) {
			return
		}
	}
	if x.Expiry != "" {
		value := protoreflect.ValueOfString(x.Expiry)
		if !f(fd_NewContract_expiry, value) {
			return
		}
	}
	if x.ShippingDelay != uint32(0) {
		value := protoreflect.ValueOfUint32(x.ShippingDelay)
		if !f(fd_NewContract_shippingDelay, value) {
			return
		}
	}
	if x.StartTime != "" {
		value := protoreflect.ValueOfString(x.StartTime)
		if !f(fd_NewContract_startTime, value) {
			return
		}
	}
	if x.DeliveryDelay != uint32(0) {
		value := protoreflect.ValueOfUint32(x.DeliveryDelay)
		if !f(fd_NewContract_deliveryDelay, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_NewContract) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "example.deal.NewContract.dealId":
		return x.DealId != ""
	case "example.deal.NewContract.contractId":
		return x.ContractId != ""
	case "example.deal.NewContract.consumer":
		return x.Consumer != ""
	case "example.deal.NewContract.desc":
		return x.Desc != ""
	case "example.deal.NewContract.ownerETA":
		return x.OwnerETA != uint32(0)
	case "example.deal.NewContract.vendorETA":
		return x.VendorETA != uint32(0)
	case "example.deal.NewContract.status":
		return x.Status != ""
	case "example.deal.NewContract.fees":
		return x.Fees != uint64(0)
	case "example.deal.NewContract.expiry":
		return x.Expiry != ""
	case "example.deal.NewContract.shippingDelay":
		return x.ShippingDelay != uint32(0)
	case "example.deal.NewContract.startTime":
		return x.StartTime != ""
	case "example.deal.NewContract.deliveryDelay":
		return x.DeliveryDelay != uint32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NewContract) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "example.deal.NewContract.dealId":
		x.DealId = ""
	case "example.deal.NewContract.contractId":
		x.ContractId = ""
	case "example.deal.NewContract.consumer":
		x.Consumer = ""
	case "example.deal.NewContract.desc":
		x.Desc = ""
	case "example.deal.NewContract.ownerETA":
		x.OwnerETA = uint32(0)
	case "example.deal.NewContract.vendorETA":
		x.VendorETA = uint32(0)
	case "example.deal.NewContract.status":
		x.Status = ""
	case "example.deal.NewContract.fees":
		x.Fees = uint64(0)
	case "example.deal.NewContract.expiry":
		x.Expiry = ""
	case "example.deal.NewContract.shippingDelay":
		x.ShippingDelay = uint32(0)
	case "example.deal.NewContract.startTime":
		x.StartTime = ""
	case "example.deal.NewContract.deliveryDelay":
		x.DeliveryDelay = uint32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_NewContract) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "example.deal.NewContract.dealId":
		value := x.DealId
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.contractId":
		value := x.ContractId
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.consumer":
		value := x.Consumer
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.desc":
		value := x.Desc
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.ownerETA":
		value := x.OwnerETA
		return protoreflect.ValueOfUint32(value)
	case "example.deal.NewContract.vendorETA":
		value := x.VendorETA
		return protoreflect.ValueOfUint32(value)
	case "example.deal.NewContract.status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.fees":
		value := x.Fees
		return protoreflect.ValueOfUint64(value)
	case "example.deal.NewContract.expiry":
		value := x.Expiry
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.shippingDelay":
		value := x.ShippingDelay
		return protoreflect.ValueOfUint32(value)
	case "example.deal.NewContract.startTime":
		value := x.StartTime
		return protoreflect.ValueOfString(value)
	case "example.deal.NewContract.deliveryDelay":
		value := x.DeliveryDelay
		return protoreflect.ValueOfUint32(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NewContract) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "example.deal.NewContract.dealId":
		x.DealId = value.Interface().(string)
	case "example.deal.NewContract.contractId":
		x.ContractId = value.Interface().(string)
	case "example.deal.NewContract.consumer":
		x.Consumer = value.Interface().(string)
	case "example.deal.NewContract.desc":
		x.Desc = value.Interface().(string)
	case "example.deal.NewContract.ownerETA":
		x.OwnerETA = uint32(value.Uint())
	case "example.deal.NewContract.vendorETA":
		x.VendorETA = uint32(value.Uint())
	case "example.deal.NewContract.status":
		x.Status = value.Interface().(string)
	case "example.deal.NewContract.fees":
		x.Fees = value.Uint()
	case "example.deal.NewContract.expiry":
		x.Expiry = value.Interface().(string)
	case "example.deal.NewContract.shippingDelay":
		x.ShippingDelay = uint32(value.Uint())
	case "example.deal.NewContract.startTime":
		x.StartTime = value.Interface().(string)
	case "example.deal.NewContract.deliveryDelay":
		x.DeliveryDelay = uint32(value.Uint())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NewContract) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "example.deal.NewContract.dealId":
		panic(fmt.Errorf("field dealId of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.contractId":
		panic(fmt.Errorf("field contractId of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.consumer":
		panic(fmt.Errorf("field consumer of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.desc":
		panic(fmt.Errorf("field desc of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.ownerETA":
		panic(fmt.Errorf("field ownerETA of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.vendorETA":
		panic(fmt.Errorf("field vendorETA of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.status":
		panic(fmt.Errorf("field status of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.fees":
		panic(fmt.Errorf("field fees of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.expiry":
		panic(fmt.Errorf("field expiry of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.shippingDelay":
		panic(fmt.Errorf("field shippingDelay of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.startTime":
		panic(fmt.Errorf("field startTime of message example.deal.NewContract is not mutable"))
	case "example.deal.NewContract.deliveryDelay":
		panic(fmt.Errorf("field deliveryDelay of message example.deal.NewContract is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_NewContract) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "example.deal.NewContract.dealId":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.contractId":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.consumer":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.desc":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.ownerETA":
		return protoreflect.ValueOfUint32(uint32(0))
	case "example.deal.NewContract.vendorETA":
		return protoreflect.ValueOfUint32(uint32(0))
	case "example.deal.NewContract.status":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.fees":
		return protoreflect.ValueOfUint64(uint64(0))
	case "example.deal.NewContract.expiry":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.shippingDelay":
		return protoreflect.ValueOfUint32(uint32(0))
	case "example.deal.NewContract.startTime":
		return protoreflect.ValueOfString("")
	case "example.deal.NewContract.deliveryDelay":
		return protoreflect.ValueOfUint32(uint32(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: example.deal.NewContract"))
		}
		panic(fmt.Errorf("message example.deal.NewContract does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_NewContract) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in example.deal.NewContract", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_NewContract) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_NewContract) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_NewContract) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_NewContract) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*NewContract)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.DealId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ContractId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Consumer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Desc)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.OwnerETA != 0 {
			n += 1 + runtime.Sov(uint64(x.OwnerETA))
		}
		if x.VendorETA != 0 {
			n += 1 + runtime.Sov(uint64(x.VendorETA))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Fees != 0 {
			n += 1 + runtime.Sov(uint64(x.Fees))
		}
		l = len(x.Expiry)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ShippingDelay != 0 {
			n += 1 + runtime.Sov(uint64(x.ShippingDelay))
		}
		l = len(x.StartTime)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.DeliveryDelay != 0 {
			n += 1 + runtime.Sov(uint64(x.DeliveryDelay))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*NewContract)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.DeliveryDelay != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DeliveryDelay))
			i--
			dAtA[i] = 0x60
		}
		if len(x.StartTime) > 0 {
			i -= len(x.StartTime)
			copy(dAtA[i:], x.StartTime)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StartTime)))
			i--
			dAtA[i] = 0x5a
		}
		if x.ShippingDelay != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ShippingDelay))
			i--
			dAtA[i] = 0x50
		}
		if len(x.Expiry) > 0 {
			i -= len(x.Expiry)
			copy(dAtA[i:], x.Expiry)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Expiry)))
			i--
			dAtA[i] = 0x4a
		}
		if x.Fees != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Fees))
			i--
			dAtA[i] = 0x40
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x3a
		}
		if x.VendorETA != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.VendorETA))
			i--
			dAtA[i] = 0x30
		}
		if x.OwnerETA != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.OwnerETA))
			i--
			dAtA[i] = 0x28
		}
		if len(x.Desc) > 0 {
			i -= len(x.Desc)
			copy(dAtA[i:], x.Desc)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Desc)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Consumer) > 0 {
			i -= len(x.Consumer)
			copy(dAtA[i:], x.Consumer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Consumer)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.ContractId) > 0 {
			i -= len(x.ContractId)
			copy(dAtA[i:], x.ContractId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ContractId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.DealId) > 0 {
			i -= len(x.DealId)
			copy(dAtA[i:], x.DealId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DealId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*NewContract)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: NewContract: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: NewContract: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DealId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DealId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ContractId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Consumer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Consumer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Desc", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Desc = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OwnerETA", wireType)
				}
				x.OwnerETA = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.OwnerETA |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VendorETA", wireType)
				}
				x.VendorETA = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.VendorETA |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
				}
				x.Fees = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Fees |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Expiry = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ShippingDelay", wireType)
				}
				x.ShippingDelay = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ShippingDelay |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StartTime = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DeliveryDelay", wireType)
				}
				x.DeliveryDelay = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DeliveryDelay |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: example/deal/new_contract.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DealId        string `protobuf:"bytes,1,opt,name=dealId,proto3" json:"dealId,omitempty"`
	ContractId    string `protobuf:"bytes,2,opt,name=contractId,proto3" json:"contractId,omitempty"`
	Consumer      string `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Desc          string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	OwnerETA      uint32 `protobuf:"varint,5,opt,name=ownerETA,proto3" json:"ownerETA,omitempty"`
	VendorETA     uint32 `protobuf:"varint,6,opt,name=vendorETA,proto3" json:"vendorETA,omitempty"`
	Status        string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Fees          uint64 `protobuf:"varint,8,opt,name=fees,proto3" json:"fees,omitempty"`
	Expiry        string `protobuf:"bytes,9,opt,name=expiry,proto3" json:"expiry,omitempty"`
	ShippingDelay uint32 `protobuf:"varint,10,opt,name=shippingDelay,proto3" json:"shippingDelay,omitempty"`
	StartTime     string `protobuf:"bytes,11,opt,name=startTime,proto3" json:"startTime,omitempty"`
	DeliveryDelay uint32 `protobuf:"varint,12,opt,name=deliveryDelay,proto3" json:"deliveryDelay,omitempty"`
}

func (x *NewContract) Reset() {
	*x = NewContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_deal_new_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContract) ProtoMessage() {}

// Deprecated: Use NewContract.ProtoReflect.Descriptor instead.
func (*NewContract) Descriptor() ([]byte, []int) {
	return file_example_deal_new_contract_proto_rawDescGZIP(), []int{0}
}

func (x *NewContract) GetDealId() string {
	if x != nil {
		return x.DealId
	}
	return ""
}

func (x *NewContract) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *NewContract) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *NewContract) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *NewContract) GetOwnerETA() uint32 {
	if x != nil {
		return x.OwnerETA
	}
	return 0
}

func (x *NewContract) GetVendorETA() uint32 {
	if x != nil {
		return x.VendorETA
	}
	return 0
}

func (x *NewContract) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NewContract) GetFees() uint64 {
	if x != nil {
		return x.Fees
	}
	return 0
}

func (x *NewContract) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *NewContract) GetShippingDelay() uint32 {
	if x != nil {
		return x.ShippingDelay
	}
	return 0
}

func (x *NewContract) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *NewContract) GetDeliveryDelay() uint32 {
	if x != nil {
		return x.DeliveryDelay
	}
	return 0
}

var File_example_deal_new_contract_proto protoreflect.FileDescriptor

var file_example_deal_new_contract_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x61, 0x6c, 0x2f, 0x6e,
	0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x64, 0x65, 0x61, 0x6c, 0x1a,
	0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x19, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x61, 0x6c,
	0x2f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x02,
	0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x45, 0x54,
	0x41, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x45, 0x54,
	0x41, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x45, 0x54, 0x41, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x45, 0x54, 0x41, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x65, 0x65, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x65, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x42, 0x8f, 0x01,
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x64, 0x65,
	0x61, 0x6c, 0x42, 0x10, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x18, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x64, 0x65, 0x61, 0x6c,
	0xa2, 0x02, 0x03, 0x45, 0x44, 0x58, 0xaa, 0x02, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x44, 0x65, 0x61, 0x6c, 0xca, 0x02, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5c,
	0x44, 0x65, 0x61, 0x6c, 0xe2, 0x02, 0x18, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5c, 0x44,
	0x65, 0x61, 0x6c, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x0d, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3a, 0x3a, 0x44, 0x65, 0x61, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_deal_new_contract_proto_rawDescOnce sync.Once
	file_example_deal_new_contract_proto_rawDescData = file_example_deal_new_contract_proto_rawDesc
)

func file_example_deal_new_contract_proto_rawDescGZIP() []byte {
	file_example_deal_new_contract_proto_rawDescOnce.Do(func() {
		file_example_deal_new_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_deal_new_contract_proto_rawDescData)
	})
	return file_example_deal_new_contract_proto_rawDescData
}

var file_example_deal_new_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_example_deal_new_contract_proto_goTypes = []interface{}{
	(*NewContract)(nil), // 0: example.deal.NewContract
}
var file_example_deal_new_contract_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_deal_new_contract_proto_init() }
func file_example_deal_new_contract_proto_init() {
	if File_example_deal_new_contract_proto != nil {
		return
	}
	file_example_deal_params_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_example_deal_new_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_deal_new_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_deal_new_contract_proto_goTypes,
		DependencyIndexes: file_example_deal_new_contract_proto_depIdxs,
		MessageInfos:      file_example_deal_new_contract_proto_msgTypes,
	}.Build()
	File_example_deal_new_contract_proto = out.File
	file_example_deal_new_contract_proto_rawDesc = nil
	file_example_deal_new_contract_proto_goTypes = nil
	file_example_deal_new_contract_proto_depIdxs = nil
}
