// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: example/deal/query.proto

package deal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName         = "/example.deal.Query/Params"
	Query_NewDeal_FullMethodName        = "/example.deal.Query/NewDeal"
	Query_NewDealAll_FullMethodName     = "/example.deal.Query/NewDealAll"
	Query_NewContract_FullMethodName    = "/example.deal.Query/NewContract"
	Query_NewContractAll_FullMethodName = "/example.deal.Query/NewContractAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a NewDeal by index.
	NewDeal(ctx context.Context, in *QueryGetNewDealRequest, opts ...grpc.CallOption) (*QueryGetNewDealResponse, error)
	// Queries a list of NewDeal items.
	NewDealAll(ctx context.Context, in *QueryAllNewDealRequest, opts ...grpc.CallOption) (*QueryAllNewDealResponse, error)
	// Queries a NewContract by index.
	NewContract(ctx context.Context, in *QueryGetNewContractRequest, opts ...grpc.CallOption) (*QueryGetNewContractResponse, error)
	// Queries a list of NewContract items.
	NewContractAll(ctx context.Context, in *QueryAllNewContractRequest, opts ...grpc.CallOption) (*QueryAllNewContractResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewDeal(ctx context.Context, in *QueryGetNewDealRequest, opts ...grpc.CallOption) (*QueryGetNewDealResponse, error) {
	out := new(QueryGetNewDealResponse)
	err := c.cc.Invoke(ctx, Query_NewDeal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewDealAll(ctx context.Context, in *QueryAllNewDealRequest, opts ...grpc.CallOption) (*QueryAllNewDealResponse, error) {
	out := new(QueryAllNewDealResponse)
	err := c.cc.Invoke(ctx, Query_NewDealAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewContract(ctx context.Context, in *QueryGetNewContractRequest, opts ...grpc.CallOption) (*QueryGetNewContractResponse, error) {
	out := new(QueryGetNewContractResponse)
	err := c.cc.Invoke(ctx, Query_NewContract_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NewContractAll(ctx context.Context, in *QueryAllNewContractRequest, opts ...grpc.CallOption) (*QueryAllNewContractResponse, error) {
	out := new(QueryAllNewContractResponse)
	err := c.cc.Invoke(ctx, Query_NewContractAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a NewDeal by index.
	NewDeal(context.Context, *QueryGetNewDealRequest) (*QueryGetNewDealResponse, error)
	// Queries a list of NewDeal items.
	NewDealAll(context.Context, *QueryAllNewDealRequest) (*QueryAllNewDealResponse, error)
	// Queries a NewContract by index.
	NewContract(context.Context, *QueryGetNewContractRequest) (*QueryGetNewContractResponse, error)
	// Queries a list of NewContract items.
	NewContractAll(context.Context, *QueryAllNewContractRequest) (*QueryAllNewContractResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) NewDeal(context.Context, *QueryGetNewDealRequest) (*QueryGetNewDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDeal not implemented")
}
func (UnimplementedQueryServer) NewDealAll(context.Context, *QueryAllNewDealRequest) (*QueryAllNewDealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewDealAll not implemented")
}
func (UnimplementedQueryServer) NewContract(context.Context, *QueryGetNewContractRequest) (*QueryGetNewContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContract not implemented")
}
func (UnimplementedQueryServer) NewContractAll(context.Context, *QueryAllNewContractRequest) (*QueryAllNewContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewContractAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewDeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNewDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewDeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewDeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewDeal(ctx, req.(*QueryGetNewDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewDealAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNewDealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewDealAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewDealAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewDealAll(ctx, req.(*QueryAllNewDealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNewContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewContract(ctx, req.(*QueryGetNewContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NewContractAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNewContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NewContractAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NewContractAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NewContractAll(ctx, req.(*QueryAllNewContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "example.deal.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "NewDeal",
			Handler:    _Query_NewDeal_Handler,
		},
		{
			MethodName: "NewDealAll",
			Handler:    _Query_NewDealAll_Handler,
		},
		{
			MethodName: "NewContract",
			Handler:    _Query_NewContract_Handler,
		},
		{
			MethodName: "NewContractAll",
			Handler:    _Query_NewContractAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/deal/query.proto",
}
